Added crop method
yasirkula/UnityTextureOps pull request #2
Opened 2020-04-20 22:26 UTC by thegoldenmule

This library has been useful, but was missing a general `Crop` method. I tried to follow convention as well as possible.

2020-04-22 07:23 UTC, yasirkula commented
Thank you for the PR, I'll take a look at it soon :)

2020-04-26 12:18 UTC, yasirkula requested changes
Thanks again for the PR. I've suggested some changes, could you please check them out?

2020-04-26 12:18 UTC, yasirkula commented on Plugins/TextureOps/TextureOps.cs
> +	public static Texture2D Crop(Texture sourceTex, int x, int y, int width, int height, TextureFormat format = TextureFormat.RGBA32, Options options = new Options())
Could you rename x to leftOffset and y to topOffset? 'y' itself can be ambiguous. In the meantime, adding spaces in between parentheses would be appreciated.

P.S. Since Crop is an essential feature, I think we can put it above the Scale function.

2020-04-26 12:18 UTC, yasirkula commented on Plugins/TextureOps/TextureOps.cs
> +
Adding these failsafe checks here would be great!

```suggestion

		if( width <= 0 || width > sourceTex.width )
			width = sourceTex.width;
		if( height <= 0 || height > sourceTex.height )
			height = sourceTex.height;

		if( leftOffset <= 0 )
			leftOffset = 0;
		else if( leftOffset + width > sourceTex.width )
			leftOffset = sourceTex.width - width;

		if( topOffset <= 0 )
			topOffset = 0;
		else if( topOffset + height > sourceTex.height )
			topOffset = sourceTex.height - height;
	
```

2020-04-26 12:18 UTC, yasirkula commented on README.md
> +`Texture2D[] TextureOps.Crop( Texture2D, sourceTex, int x, int y, int width, int height, TextureFormat format = TextureFormat.RGBA32, TextureOps.Options options )`: cuts a rectangle out of the source
x and y here needs to be renamed, as well. We can move this function to above the Scale function. And I'd recommend changing the description as follows:

> crops *sourceTex* and returns the cropped texture.

2020-04-27 18:35 UTC, thegoldenmule commented
Addressed feedback.

2020-04-28 08:26 UTC, yasirkula approved these changes
Thanks!

2020-04-28 08:26 UTC, merged